{% set name = "mvt" %}
{% set version = "2.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mvt-{{ version }}.tar.gz
  sha256: d2fa6b3ecc6d64e6dadd7b7272d18c2acf860407004625e86cdbd468e963a019

build:
  number: 0
  noarch: python
  entry_points:
    - mvt-ios = mvt.ios:cli
    - mvt-android = mvt.android:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - click >=8.1.3
    - rich >=12.6.0
    - tld >=0.12.6
    - requests >=2.28.1
    - simplejson >=3.17.6
    - packaging >=21.3
    - appdirs >=1.4.4
    - iOSbackup >=0.9.923
    - adb-shell >=0.4.3
    - libusb1 >=3.0.0
    - cryptography >=38.0.1
    - pyyaml >=6.0
    - pyahocorasick >=2.0.0

test:
  imports:
    - mvt
    - mvt.android
  commands:
    - pip check
    - mvt-ios --help
    - mvt-android --help
  requires:
    - pip

about:
  home: https://github.com/mvt-project/mvt
  summary: Mobile Verification Toolkit
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://docs.mvt.re/

extra:
  recipe-maintainers:
    - ickc
