{% set name = "mvt" %}
{% set version = "1.2.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mvt-{{ version }}.tar.gz
  sha256: 74044ac6d6f6f6d62fde38ad89816253741b126eddc0dfbe10639e913fbf7bc7

build:
  number: 0
  noarch: python
  entry_points:
    - mvt-ios = mvt.ios:cli
    - mvt-android = mvt.android:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - packaging >=21.0
    - requests >=2.26.0
  run:
    - adb-shell >=0.4.2
    - click >=8.0.3
    - iosbackup >=0.9.921
    - libusb1 >=2.0.1
    - packaging >=21.0
    - python >=3.6
    - requests >=2.26.0
    - rich >=10.12.0
    - simplejson >=3.17.5
    - tld >=0.12.6
    - tqdm >=4.62.3

test:
  imports:
    - mvt
    - mvt.android
  commands:
    - pip check
    - mvt-ios --help
    - mvt-android --help
  requires:
    - pip

about:
  home: https://github.com/mvt-project/mvt
  summary: Mobile Verification Toolkit
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://docs.mvt.re/

extra:
  recipe-maintainers:
    - ickc
